### ISSUE TITLE
Javascript icon hard to read

### ISSUE THREAD

**Issue by phaedryx** [fv0/native-ui#1]
<img width="237" alt="js-icon" src="https://cloud.githubusercontent.com/assets/288994/10412035/8816382e-6f36-11e5-9ddc-53d492d59628.png">

Not a bit deal, but hard to read.

**Comment by fv0** [comment]
Hey @phaedryx, this is due to the nature of the light theme. If you take the grayscale icons it should work fine. You can apply this in the settings of the package _file-icons_. This will work better with a "dark" theme, which I might be working on in the future.

Thanks for your post.

**Comment by int3h** [comment]
@phaedryx I noticed this very same problem with the file-icons package. It turns out that file-icons includes a better JS icon already, but it isn't used by default. 

To fix that, I have the following snippet in my user `styles.less` (editable via `Atom->Stylesheet...`):

```less
// Change the icon for JavaScript files from a thin, hard-to-see outline, to a beefy block icon
.custom-js-icon() {
  @import "../../../../../.atom/packages/file-icons/styles/icons";
  @import "../../../../../.atom/packages/file-icons/styles/items";

  .js-custom-icon { .mf; content: "\f129"; font-size: large; }

  @{pane-tab-override}, .icon-file-text {
    &[data-name$=".js"]:before,
    &[data-name$=".es6"]:before,
    &[data-name$=".es"]:before,
    &[data-name$=".js.erb"]:before  {
      .js-custom-icon;
    }
  }
}
.custom-js-icon();
```

Screen shot:
![screen shot 2016-12-09 at 4 58 53 pm](https://cloud.githubusercontent.com/assets/567398/21069641/caa59014-be30-11e6-9a59-4f10765c45f4.png)
