### ISSUE TITLE
v0.18.1 hides tabs

### ISSUE THREAD

**Issue by paulozoom** [fv0/native-ui#55]
After updating to the latest version, the tabs were immediately gone:

![screen capture on 2016-05-10 at 16-21-13](https://cloud.githubusercontent.com/assets/69427/15149834/6124d742-16cb-11e6-86a4-ca0003f0548f.gif)

**Comment by fv0** [comment]
@paulozoom It works fine on my machine. What other packages have you got installed? Unfortunately I wasn't able to reproduce the missing tab bar you got.

**Comment by jsmecham** [comment]
I also see this behavior.

**Comment by fv0** [comment]
@paulozoom @jsmecham 
I think this might have to do with #47. Could you open the package and delete or comment lines 25–27 in `styles/panels.less`? Tell me if it works, then I will remove that part and publish a patch version.

Thanks for your help.

``` less
atom-panel-container.left:empty + atom-workspace-axis .tab-bar {
  display: none;
}
```
