### ISSUE TITLE
System colors

### ISSUE THREAD

**Issue by simurai** [fv0/native-ui#56]
So @kevinSuttle dug up this old (2009!) post about using the [system colors in CSS](https://www.sitepoint.com/css-system-styles/). And the cool part is that it adapts to the changes in the settings:

![colors](https://cloud.githubusercontent.com/assets/378023/15594793/fd76a7c6-23f3-11e6-95f9-57e9cc0decdb.gif)

> [CodePen Demo](http://codepen.io/kevinSuttle/pen/pbzxZZ)

Might be neat to use them in this theme?

**Comment by kevinSuttle** [comment]
Works. 

![electron-css-system-properties](https://cloud.githubusercontent.com/assets/95672/15598466/69357e02-23a8-11e6-81de-a475bcf8bc8e.gif)

**Comment by fv0** [comment]
This looks very cool. Thanks to both of you. I'll implement this and test it. That would be a great step forward.

**Comment by fv0** [comment]
Closed because not cross-platform compatible.

**Comment by kevinSuttle** [comment]
Can you explain that?

**Comment by fv0** [comment]
@kevinSuttle I can’t imagine that the colors appear exactly the same on every OS. What do you think?

**Comment by kevinSuttle** [comment]
They don't appear the same, no.

**Comment by simurai** [comment]
You could scope it to only macOS with the `.platform-darwin` class.

``` less
.selected {
  background-color: @background-color-selected; // fallback
}

.platform-darwin .selected {
  color: HighlightText;
  background-color: Highlight;
}
```

but not sure.. maybe that's too much work to maintain for many 3rd party packages.
