### ISSUE TITLE
Don't hide text editor's scroll bar

### ISSUE THREAD

**Issue by int3h** [fv0/native-ui#62]
Right now, [atom.less](https://github.com/fv0/native-ui/blob/master/styles/atom.less) hides all scroll bars in Atom, using the following code:

```less
// Remove visible scrollbars but don't prevent scrolling
::-webkit-scrollbar {
  display: none;
}
```

Before Atom v1.13.0, this rule didn't affect the scroll bars of `atom-text-editor` elements, because those used a shadow DOM that insulated it from this global style. Atom v.1.13.0-beta0 removed the shadow DOM, though, and now native-ui hides scroll bars in the editor.

Recent updated in native-ui have fixed most shadow DOM problems, but this one remains. It's also annoying because there's no easy way to disable/override this style from subsequent rules (like from the user stylesheet).

native-ui probably still wants to hide stylesheets in most elements besides the text editor, but perhaps a white-list of these elements are more appropriate than a global style?
