### ISSUE TITLE
Atom 1.17beta Docks

### ISSUE THREAD

**Issue by lexicalunit** [fv0/native-ui#69]
Docks are a [new feature in Atom 1.17beta](http://blog.atom.io/2017/04/12/atom-1-16.html#introducing-docks). Currently they look a bit weird under `native-ui`.

![screen shot 2017-04-18 at 10 31 18 am](https://cloud.githubusercontent.com/assets/1903876/25139188/2fcba422-2422-11e7-83ff-106a22297f5e.png)

I was able to tweak things a little using my `styles.less`:

```less
@import "syntax-variables";
@import "ui-variables";

.theme-native-ui {
  .atom-dock-resize-handle {
      width: 2px;
      background-color: @base-border-color;
      border-radius: 0;
      border: 0;
      margin: 0;
      padding: 0;
  }

  atom-dock {
    .tab-bar.list-inline.inset-panel {
      border: 0;
      border-right: 1px solid @base-border-color;
      border-radius: 0;
      padding: 0;
    }
  }

  .tab-bar {
    border-radius: 0;
  }
}
```

![screen shot 2017-04-18 at 10 33 07 am](https://cloud.githubusercontent.com/assets/1903876/25139317/823f7972-2422-11e7-8ae3-88022d9cd143.png)
