### ISSUE TITLE
Hard to see git diff

### ISSUE THREAD

**Issue by McCrisp** [fv0/native-ui#80]
![screen shot 2017-09-15 at 14 44 46](https://user-images.githubusercontent.com/13944443/30482747-84d9b256-9a24-11e7-9249-feb6bc2db36c.png)

Line 9 and 11 have changes to git, but the grey styling makes it almost impossible to see the differences.

Edit: Seems like it is the styling on .atom-text-editor .line-number, setting opacity to 0.6
The border color for changed lines is already pretty dark, and with this opacity it almost disappear.

**Comment by fv0** [comment]
This is a hard one since the default styling is coming from Atom itself and it’s not Native UI changing this. I don’t feel well implementing this, since I don’t know what kind of syntax theme people will be using and it might interfere with this.

I’d suggest the following changes for your user stylesheet:

- Make the border thicker.
  ```less
  atom-text-editor .gutter .line-number.git-line-modified {
    border-left-width: 4px;
    padding-left: calc(0.5em - 5px);
  }
  // Repeat for other Git changes
  ```
- Increase the opacity of the gutter.
  ```less
  atom-text-editor .line-number {
    opacity: 1;
  }
  ```

Does this help?
